# Generated by Django 4.2.5 on 2023-10-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='user',
        ),
    ]
