# Generated by Django 4.2.5 on 2023-10-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_remove_quotes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='quotes',
            field=models.TextField(max_length=255),
        ),
    ]
