# Generated by Django 4.2.6 on 2023-12-15 14:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('likes_count', models.IntegerField(default=False)),
                ('dislikes_count', models.IntegerField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('review', models.TextField(max_length=1000, null=True)),
                ('rating', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Minimum rating is 0!'), django.core.validators.MaxValueValidator(100, message='Maximum rating is 100!')])),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
