# Generated by Django 4.2.4 on 2023-10-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_item_books_alter_item_rating_alter_item_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date_added',
        ),
        migrations.AddField(
            model_name='item',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
