# Generated by Django 4.2.6 on 2023-12-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='books',
        ),
    ]
