# Generated by Django 4.2.6 on 2023-12-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
