# Generated by Django 4.2.4 on 2023-10-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_item_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-date_added']},
        ),
    ]
