# Generated by Django 4.2.4 on 2023-10-27 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_alter_item_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Minimum rating is 0!'), django.core.validators.MaxValueValidator(100, message='Maximum rating is 100!')]),
        ),
    ]
