# Generated by Django 4.2.4 on 2023-10-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_item_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dislikes_count',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='likes_count',
            field=models.IntegerField(default=False),
        ),
    ]
