# Generated by Django 4.2.4 on 2023-10-27 05:45

from django.db import migrations
from django.core.management import call_command


def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "databasebooks.json")

class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_image'),
    ]

    operations = [
    migrations.RunPython(load_my_initial_data),
]
